### ISSUE TITLE
CRAN comments (for Colin)

### ISSUE THREAD

**Issue by txm676** [txm676/gambin#2]
"gam-bin" stands for "gamma-binomial". Ideally, if you could also add p, q, r functions for the gambin distribution, it would be great. "

**Comment by mkborregaard** [comment]
"gam-bin" is short for "gamma-binomial" is already in the DESCRIPTION file - it is the p, q and r functions that are missing - I mean the functionality is there, but they need to be named right, have the right arguments etc for those types of functions.

**Comment by csgillespie** [comment]
@mkborregaard @txm676 How much lee-way do I have making function names and arguments consistent. For example, 

 * `dgambin` The first argument should be `x`
 * Then we have `fitGambin` and `create_octaves` functions.

In my opinion, it would be cleaner to completely refactor the code and bump the version number. Especially since the overall goal is to have a mixture model which will have additional parameters.

Of course, this is a pain for existing users.

**Comment by txm676** [comment]
That's fine with me, it is probably better in the long run to have it consistent

**Comment by mkborregaard** [comment]
@csgillespie IMHO we should go for consistency but do our best to ease the transition, so it should fail noisily, with an error message clearly specifying what happened. I'll see if I can check if any other CRAN packages depend on gambin and contact the authors - do you know out of hand how to do that?

**Comment by mkborregaard** [comment]
But please make all breaking changes in one branch, we will merge all at once instead of gradually adjusting. We can talk about it in detail when when we have the PR.

**Comment by csgillespie** [comment]
@mkborregaard @txm676 Nothing depends on gambin; the easiest way is to go to the CRAN page: https://cran.r-project.org/web/packages/gambin/index.html There are no Reverse dependencies.

One possibility is to release a new package gambin2 (say) that contains the mixture models and nicely deprecate gambin for the next year. We can work out the details later.

**Comment by mkborregaard** [comment]
Absolutely, let us take the discussion when we see the extent of the changes, but basically were pretty open to changes that improve consistency and usefulness. My preference would be to continue the gambin package and fail with a clear error message on misspecifications.

**Comment by csgillespie** [comment]
I've made a (good) first pass through the package (https://github.com/csgillespie/gambin). The major changes are:

  * Code refactored
  * Create r/q/p/d gambin functions
  * Created an initial vignette.
  * Created an initial test suite
  * Hooked up to travis and codecov
  * Created `d/r/p/q` functions
  * Minor optimisation on `fitGam`
  * Move `plot` to `barplot`, `lines`, `points`. You can now pass standard plotting arguments 
  and everything will work as expected.
  * Created `README.Rmd` to generate `README.md`
  * Created NEWS.md  
  * Updated DESCRIPTION with URL and bugreports

The package is now called `gambin2` This was to help with my testing. It's up to you whether the major changes warrant a package name change. Comments welcome.

**Comment by mkborregaard** [comment]
This is amazing - can you make a PR? That will make it easy to review the changes.
:sparkles:

**Comment by csgillespie** [comment]
Do you want gambin v2.0.0 or gambin2 v 0.0.1?

**Comment by mkborregaard** [comment]
let us aim for v2.0.0 - once we have talked about your suggested changes and yours and @txm676 's current ideas for progressing the package we should talk about how to organize development - sounds good?

**Comment by txm676** [comment]
Yeah thanks Colin, that all looks really great! Can't see any issues or
anything.

Cheers,
Tom

**Comment by mkborregaard** [comment]
Hey @csgillespie thanks for the great work you are doing in updating this package. I was a little confused, I was thinking you were aspiring to take over the role of CRAN maintainer for this package so I wrote @txm676 yesterday to discuss whether he thought this could be a good idea - and explained that you're just helping him modernizing it. That's great, I understand much better now :-)
Please let me know how I can help you best - is the reason that you haven't made a pull request that you want to keep open the possibility of a gambin2? I just find it a useful format for discussing the changes line by line.
By the way, I did look at your fork, and it is a pleasure to see your R code :-)

**Comment by mkborregaard** [comment]
Honestly, I don't actively develop my R packages at the moment, as I am turning more and more of attention to Julia. You should join us, the grass is greener!

**Comment by csgillespie** [comment]
The only reason I've not made a PR is because I'm still tweaking at the edges. That's easier in the privacy (?) of my own repo ;)
