### ISSUE TITLE
Travis and Codecov

### ISSUE THREAD

**Issue by csgillespie** [txm676/gambin#6]
In order for the icons to work (and the associated tests) on the README, you need to sign up for 

 * [travis](https://travis-ci.org/) - continuous integration testing
 * [codecov](https://codecov.io/) - code coverage.

**Comment by mkborregaard** [comment]
I have signed up (I use Travis elsewhere as well but I am not very experienced with it), and have just pushed an empty commit to trigger the build. Let us see if it works.

**Comment by csgillespie** [comment]
Both seem to working.
